client_config_backend: settings
client_config:
  client_id: 969158993379-1t5i72331p1f6rijnmq3qqrqmbgspcfo.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install